[package]
name = "ruby-fork-test"
version = "0.1.0"
authors = ["Julia Evans <julia@stripe.com>"]

[dependencies]
"read-process-memory" = "0.1.2"
"libc" = "0.2.36"
"elf" = "0.0.10"
"failure" = "0.1.1"
